/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Camila_Camera
 */
public class GUITelaCadastroUsuariollFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUITelaCadastroUsuariollFrame
     */
    public GUITelaCadastroUsuariollFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTipodeRenda = new javax.swing.JLabel();
        jrbMais3 = new javax.swing.JRadioButton();
        jrbTrabalhoInformal = new javax.swing.JRadioButton();
        jrbCLT = new javax.swing.JRadioButton();
        jrbMEI = new javax.swing.JRadioButton();
        jrbRendaFixa = new javax.swing.JRadioButton();
        jrbEmpresaPP = new javax.swing.JRadioButton();
        jrbRendaVariavel = new javax.swing.JRadioButton();
        jrbMediaEmpresa = new javax.swing.JRadioButton();
        jrbAte1 = new javax.swing.JRadioButton();
        jlNegocio = new javax.swing.JLabel();
        jrbAte2 = new javax.swing.JRadioButton();
        jlRenda = new javax.swing.JLabel();
        jrbAte3 = new javax.swing.JRadioButton();
        jbSalvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTipodeRenda.setText("Tipo de Renda:");

        jrbMais3.setText("Mais de 3 salários minímos");

        jrbTrabalhoInformal.setText("Trabalho Informal");
        jrbTrabalhoInformal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTrabalhoInformalActionPerformed(evt);
            }
        });

        jrbCLT.setText("Trabalhador Formal (CLT)");

        jrbMEI.setText("MEI (Micro Empreendedor Individual - Autônomo)");
        jrbMEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMEIActionPerformed(evt);
            }
        });

        jrbRendaFixa.setText("Renda Fixa");

        jrbEmpresaPP.setText("Empresa de Pequeno Porte");
        jrbEmpresaPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEmpresaPPActionPerformed(evt);
            }
        });

        jrbRendaVariavel.setText("Renda Variável");

        jrbMediaEmpresa.setText("Média Empresa");

        jrbAte1.setText("Até 1 salário minímo");
        jrbAte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAte1ActionPerformed(evt);
            }
        });

        jlNegocio.setText("Especificação de Negócio do Usuário:");

        jrbAte2.setText("Até 2 salários minímos");

        jlRenda.setText("Renda:");

        jrbAte3.setText("Até 3 salários minímos");

        jbSalvar.setText("Salvar e continuar");

        jButton1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbRendaFixa)
                    .addComponent(jrbCLT)
                    .addComponent(jlTipodeRenda)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jrbRendaVariavel)
                            .addGap(180, 180, 180)
                            .addComponent(jbSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlNegocio)
                                .addComponent(jrbTrabalhoInformal)
                                .addComponent(jrbMEI)
                                .addComponent(jrbEmpresaPP)
                                .addComponent(jrbMediaEmpresa))
                            .addGap(171, 171, 171)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jrbMais3)
                                .addComponent(jrbAte3)
                                .addComponent(jrbAte2)
                                .addComponent(jrbAte1)
                                .addComponent(jlRenda)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNegocio)
                    .addComponent(jlRenda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbTrabalhoInformal)
                    .addComponent(jrbAte1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMEI)
                    .addComponent(jrbAte2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbEmpresaPP)
                    .addComponent(jrbAte3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMediaEmpresa)
                    .addComponent(jrbMais3))
                .addGap(18, 18, 18)
                .addComponent(jrbCLT)
                .addGap(33, 33, 33)
                .addComponent(jlTipodeRenda)
                .addGap(18, 18, 18)
                .addComponent(jrbRendaFixa)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jrbRendaVariavel)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSalvar)
                            .addComponent(jButton1))
                        .addGap(69, 69, 69))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbTrabalhoInformalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTrabalhoInformalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTrabalhoInformalActionPerformed

    private void jrbMEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMEIActionPerformed

    private void jrbEmpresaPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEmpresaPPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEmpresaPPActionPerformed

    private void jrbAte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAte1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITelaCadastroUsuariollFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITelaCadastroUsuariollFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlNegocio;
    private javax.swing.JLabel jlRenda;
    private javax.swing.JLabel jlTipodeRenda;
    private javax.swing.JRadioButton jrbAte1;
    private javax.swing.JRadioButton jrbAte2;
    private javax.swing.JRadioButton jrbAte3;
    private javax.swing.JRadioButton jrbCLT;
    private javax.swing.JRadioButton jrbEmpresaPP;
    private javax.swing.JRadioButton jrbMEI;
    private javax.swing.JRadioButton jrbMais3;
    private javax.swing.JRadioButton jrbMediaEmpresa;
    private javax.swing.JRadioButton jrbRendaFixa;
    private javax.swing.JRadioButton jrbRendaVariavel;
    private javax.swing.JRadioButton jrbTrabalhoInformal;
    // End of variables declaration//GEN-END:variables
}
