/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Camila_Camera
 */
public class GUITelaCadastroUsuariolll extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroUsuariolll
     */
    public GUITelaCadastroUsuariolll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaMotivo = new javax.swing.JTextArea();
        jlHabitacao = new javax.swing.JLabel();
        jrbAluguel = new javax.swing.JRadioButton();
        jrbProprio = new javax.swing.JRadioButton();
        jlDivida = new javax.swing.JLabel();
        jtfDivida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfDataEndividadmento = new javax.swing.JTextField();
        jlSituacao = new javax.swing.JLabel();

        setClosable(true);

        jtaMotivo.setColumns(20);
        jtaMotivo.setRows(5);
        jScrollPane1.setViewportView(jtaMotivo);

        jlHabitacao.setText("Situação de Habitação:");

        jrbAluguel.setText("Aluguel");

        jrbProprio.setText("Próprio");

        jlDivida.setText("Tamanho da Dívida:");

        jtfDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDividaActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial do Endividamento:");

        jtfDataEndividadmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataEndividadmentoActionPerformed(evt);
            }
        });

        jlSituacao.setText("Situação do Usuário (Motivo da dívida e consultoria): ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbAluguel)
                        .addGap(18, 18, 18)
                        .addComponent(jrbProprio))
                    .addComponent(jlHabitacao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlSituacao)
                        .addComponent(jLabel1)
                        .addComponent(jtfDataEndividadmento)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDivida)
                            .addComponent(jtfDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(227, 227, 227)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfDataEndividadmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlHabitacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAluguel)
                    .addComponent(jrbProprio))
                .addGap(18, 18, 18)
                .addComponent(jlDivida)
                .addGap(18, 18, 18)
                .addComponent(jtfDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDividaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDividaActionPerformed

    private void jtfDataEndividadmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataEndividadmentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataEndividadmentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlDivida;
    private javax.swing.JLabel jlHabitacao;
    private javax.swing.JLabel jlSituacao;
    private javax.swing.JRadioButton jrbAluguel;
    private javax.swing.JRadioButton jrbProprio;
    private javax.swing.JTextArea jtaMotivo;
    private javax.swing.JTextField jtfDataEndividadmento;
    private javax.swing.JTextField jtfDivida;
    // End of variables declaration//GEN-END:variables
}
